# Form implementation generated from reading ui file 'C:/OneDrive/Vioprint/OneDrive - Vioprint/software projecten/MediaOrganizer/gui/MediaOrganizerGui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1514, 870)
        self.btnExportList = QtWidgets.QPushButton(parent=Dialog)
        self.btnExportList.setGeometry(QtCore.QRect(10, 250, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExportList.sizePolicy().hasHeightForWidth())
        self.btnExportList.setSizePolicy(sizePolicy)
        self.btnExportList.setObjectName("btnExportList")
        self.btnSearchSelectedLocation = QtWidgets.QPushButton(parent=Dialog)
        self.btnSearchSelectedLocation.setGeometry(QtCore.QRect(40, 70, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearchSelectedLocation.sizePolicy().hasHeightForWidth())
        self.btnSearchSelectedLocation.setSizePolicy(sizePolicy)
        self.btnSearchSelectedLocation.setObjectName("btnSearchSelectedLocation")
        self.btnStartMainwindow = QtWidgets.QPushButton(parent=Dialog)
        self.btnStartMainwindow.setGeometry(QtCore.QRect(860, 40, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartMainwindow.sizePolicy().hasHeightForWidth())
        self.btnStartMainwindow.setSizePolicy(sizePolicy)
        self.btnStartMainwindow.setObjectName("btnStartMainwindow")
        self.listFoundedItemsNok = QtWidgets.QListWidget(parent=Dialog)
        self.listFoundedItemsNok.setGeometry(QtCore.QRect(390, 80, 591, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFoundedItemsNok.sizePolicy().hasHeightForWidth())
        self.listFoundedItemsNok.setSizePolicy(sizePolicy)
        self.listFoundedItemsNok.setObjectName("listFoundedItemsNok")
        self.lineScriptLocationMedia = QtWidgets.QLineEdit(parent=Dialog)
        self.lineScriptLocationMedia.setGeometry(QtCore.QRect(40, 40, 511, 20))
        self.lineScriptLocationMedia.setObjectName("lineScriptLocationMedia")
        self.btnBladerenLocation = QtWidgets.QPushButton(parent=Dialog)
        self.btnBladerenLocation.setGeometry(QtCore.QRect(560, 40, 80, 20))
        self.btnBladerenLocation.setObjectName("btnBladerenLocation")
        self.listFoundedItems = QtWidgets.QTreeWidget(parent=Dialog)
        self.listFoundedItems.setGeometry(QtCore.QRect(10, 290, 1331, 531))
        self.listFoundedItems.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listFoundedItems.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listFoundedItems.setObjectName("listFoundedItems")
        self.listFoundedItems.header().setVisible(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnExportList.setText(_translate("Dialog", "Resultaat opslaan"))
        self.btnSearchSelectedLocation.setText(_translate("Dialog", "Zoek in locatie"))
        self.btnStartMainwindow.setText(_translate("Dialog", "Start voorstelling"))
        self.btnBladerenLocation.setText(_translate("Dialog", "Bladeren"))
        self.listFoundedItems.setSortingEnabled(True)
        self.listFoundedItems.headerItem().setText(0, _translate("Dialog", "Map"))
        self.listFoundedItems.headerItem().setText(1, _translate("Dialog", "Aantal foto\'s"))
        self.listFoundedItems.headerItem().setText(2, _translate("Dialog", "Aantal video\'s"))
