# Form implementation generated from reading ui file 'C:/OneDrive/Vioprint/OneDrive - Vioprint/software projecten/MediaOrganizer/gui/MediaOrganizerGui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1110, 825)
        self.btnSearchAll = QtWidgets.QPushButton(parent=Dialog)
        self.btnSearchAll.setGeometry(QtCore.QRect(40, 10, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearchAll.sizePolicy().hasHeightForWidth())
        self.btnSearchAll.setSizePolicy(sizePolicy)
        self.btnSearchAll.setObjectName("btnSearchAll")
        self.listFoundedItems = QtWidgets.QListWidget(parent=Dialog)
        self.listFoundedItems.setGeometry(QtCore.QRect(250, 100, 341, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFoundedItems.sizePolicy().hasHeightForWidth())
        self.listFoundedItems.setSizePolicy(sizePolicy)
        self.listFoundedItems.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listFoundedItems.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listFoundedItems.setTextElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.listFoundedItems.setObjectName("listFoundedItems")
        self.btnSearchSelectedLocation = QtWidgets.QPushButton(parent=Dialog)
        self.btnSearchSelectedLocation.setGeometry(QtCore.QRect(40, 70, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearchSelectedLocation.sizePolicy().hasHeightForWidth())
        self.btnSearchSelectedLocation.setSizePolicy(sizePolicy)
        self.btnSearchSelectedLocation.setObjectName("btnSearchSelectedLocation")
        self.btnStartMainwindow = QtWidgets.QPushButton(parent=Dialog)
        self.btnStartMainwindow.setGeometry(QtCore.QRect(40, 150, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartMainwindow.sizePolicy().hasHeightForWidth())
        self.btnStartMainwindow.setSizePolicy(sizePolicy)
        self.btnStartMainwindow.setObjectName("btnStartMainwindow")
        self.comboSelectTypeMain = QtWidgets.QComboBox(parent=Dialog)
        self.comboSelectTypeMain.setGeometry(QtCore.QRect(40, 110, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSelectTypeMain.sizePolicy().hasHeightForWidth())
        self.comboSelectTypeMain.setSizePolicy(sizePolicy)
        self.comboSelectTypeMain.setObjectName("comboSelectTypeMain")
        self.comboSelectTypeMain.addItem("")
        self.comboSelectTypeMain.addItem("")
        self.comboSelectTypeMain.addItem("")
        self.listFoundedItemsNok = QtWidgets.QListWidget(parent=Dialog)
        self.listFoundedItemsNok.setGeometry(QtCore.QRect(700, 100, 341, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFoundedItemsNok.sizePolicy().hasHeightForWidth())
        self.listFoundedItemsNok.setSizePolicy(sizePolicy)
        self.listFoundedItemsNok.setObjectName("listFoundedItemsNok")
        self.lineScriptLocationMedia = QtWidgets.QLineEdit(parent=Dialog)
        self.lineScriptLocationMedia.setGeometry(QtCore.QRect(40, 40, 511, 20))
        self.lineScriptLocationMedia.setObjectName("lineScriptLocationMedia")
        self.btnBladerenLocation = QtWidgets.QPushButton(parent=Dialog)
        self.btnBladerenLocation.setGeometry(QtCore.QRect(560, 40, 80, 20))
        self.btnBladerenLocation.setObjectName("btnBladerenLocation")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnSearchAll.setText(_translate("Dialog", "Zoek in computer"))
        self.btnSearchSelectedLocation.setText(_translate("Dialog", "Zoek in locatie"))
        self.btnStartMainwindow.setText(_translate("Dialog", "Start voorstelling"))
        self.comboSelectTypeMain.setItemText(0, _translate("Dialog", "Foto\'s"))
        self.comboSelectTypeMain.setItemText(1, _translate("Dialog", "Films"))
        self.comboSelectTypeMain.setItemText(2, _translate("Dialog", "Beide"))
        self.btnBladerenLocation.setText(_translate("Dialog", "Bladeren"))
