# Form implementation generated from reading ui file 'C:/OneDrive/Vioprint/OneDrive - Vioprint/software projecten/MediaOrganizer/gui/MediaOrganizerGui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1110, 825)
        self.btnSearchAll = QtWidgets.QPushButton(parent=Dialog)
        self.btnSearchAll.setGeometry(QtCore.QRect(40, 30, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearchAll.sizePolicy().hasHeightForWidth())
        self.btnSearchAll.setSizePolicy(sizePolicy)
        self.btnSearchAll.setObjectName("btnSearchAll")
        self.listFoundedItems = QtWidgets.QListWidget(parent=Dialog)
        self.listFoundedItems.setGeometry(QtCore.QRect(220, 30, 941, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFoundedItems.sizePolicy().hasHeightForWidth())
        self.listFoundedItems.setSizePolicy(sizePolicy)
        self.listFoundedItems.setObjectName("listFoundedItems")
        self.btnSearchSelectedLocation = QtWidgets.QPushButton(parent=Dialog)
        self.btnSearchSelectedLocation.setGeometry(QtCore.QRect(40, 70, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearchSelectedLocation.sizePolicy().hasHeightForWidth())
        self.btnSearchSelectedLocation.setSizePolicy(sizePolicy)
        self.btnSearchSelectedLocation.setObjectName("btnSearchSelectedLocation")
        self.btnStartMainwindow = QtWidgets.QPushButton(parent=Dialog)
        self.btnStartMainwindow.setGeometry(QtCore.QRect(50, 260, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartMainwindow.sizePolicy().hasHeightForWidth())
        self.btnStartMainwindow.setSizePolicy(sizePolicy)
        self.btnStartMainwindow.setObjectName("btnStartMainwindow")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnSearchAll.setText(_translate("Dialog", "Zoek in computer"))
        self.btnSearchSelectedLocation.setText(_translate("Dialog", "Zoek in locatie"))
        self.btnStartMainwindow.setText(_translate("Dialog", "Start voorstelling"))
